- name: Download Calico manifest
  get_url:
    url: https://docs.projectcalico.org/v3.8/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: 0644
    owner: root
    group: root

- name: Set Pod network
  lineinfile:
    path: /tmp/calico.yaml
    regexp: '^(.*)value: \"192\.168\.0\.0\/16\"'
    line: '\1value: "{{ pod_network }}"'
    backrefs: yes

- name: Install Calico
  become: false
  command: kubectl create -f /tmp/calico.yaml
