---
- name: hack to resolve Problem with MergeList Issue
  command: 'apt-get clean && apt-get udpate'

- name: Install commons packages
  apt:
    name: "{{ packages }}"
    state: present
    autoclean: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: hack to resolve Problem with MergeList Issue
  command: 'apt-get clean'

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install Docker
  apt:
    name: "{{ packages }}"
    state: present
    autoclean: yes
  vars:
    packages:
      - docker-ce=18.06.3~ce~3-0~ubuntu

- name: Configure Docker daemon
  copy: src=daemon.json dest=/etc/docker/daemon.json

- name: Create Docker daemon directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Docker daemon
  systemd:
    state: restarted
    name: docker
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker
  notify:
    - docker status
