---
- name: Remove swap partition from fstab
  mount:
    name: "{{ item }}"
    state: absent
    fstype: swap
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
